name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install deps (warm cache)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain + cache + install
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'

  test:
    name: Tests (Vitest + coverage)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain + cache + install
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'
      - name: Run tests with coverage
        run: pnpm nx run api:test -- --coverage

  scan:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain + cache + install
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
